### ISSUE TITLE
Unresolved dependencies: Could not resolve project :android-patchql.

### ISSUE THREAD

**Issue by Musickiller** [sunrise-choir/sunrise-social-android-app#3]
Hi,

I've cloned the project as it is stated in the ReadMe, set up the environment and got a graddle sync error o_O

Trying to find more info about the issue now.

Relevant logs:
Sync:
```
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :android-patchql. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :android-patchql. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :android-patchql. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :android-patchql. Show Details Affected Modules: app |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :android-patchql. Show Details Affected Modules: app |  
```

Build Output:
```
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':app:compileDebugAidl'.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
	... 109 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve project :android-patchql.
Required by:
    project :app
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: Unable to find a matching configuration of project :android-patchql:
  - None of the consumable configurations have attributes.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Musickiller** [comment]
Sorry, cloned ssb-patchql instead of ssb-patchql-android. How do I delete this issue?)
