### ISSUE TITLE
Unable to build: Unsupported Modules and failed to load ssb-patchql-core

### ISSUE THREAD

**Issue by Musickiller** [sunrise-choir/sunrise-social-android-app#4]
Hi again, now I have another issue, and already have tried to find a way to fix it. (No luck with that)

As I load the project in the Android studio, I get this message:
```
Unsupported Modules Detected: Compilation is not supported for following modules: sunrise-social-android-app. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
```

Then, when I try to build and run the app, I get an error from Android Gradle Plugin, stating:
```
failed to load source for a dependency on `ssb-patchql-core`
```

Other messages in the Studio state next:
Kotlin compler:
```
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: android.databinding.annotationprocessor.ProcessDataBinding (DYNAMIC).
```
Run build:
```
org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':android-patchql:cargoBuildArm'.
***
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':android-patchql:cargoBuildArm'.
***
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cargo'' finished with non-zero exit value 101
***
       at com.nishtahir.CargoBuildTask$build$$inlined$with$lambda$1.execute(CargoBuildTask.kt:175)
	at com.nishtahir.CargoBuildTask$build$$inlined$with$lambda$1.execute(CargoBuildTask.kt:11)
```

**Comment by pietgeursen** [comment]
Hi @Musickiller 

> Unsupported Modules Detected: Compilation is not supported for following modules: sunrise-social-android-app. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

I googled that error on S.O. and got [this](https://stackoverflow.com/questions/28668252/android-studio-error-unsupported-modules-detected-compilation-is-not-supported/46988935). Can you try out some of those solutions.

> w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: android.databinding.annotationprocessor.ProcessDataBinding (DYNAMIC).

This is fine, it's just a warning, I see it too.

> Process 'command 'cargo'' finished with non-zero exit value 101

Do you have rust installed?

Also: 

What version are you running of
- rust
- android studio
- android sdk
- ndk
- java

What O.S. are you on?

**Comment by Musickiller** [comment]
@pietgeursen I'm here for a short time only, so I'll append info here as it becomes available.

## A problem with Sync:

I've tried an option to delete .idea folder and .iml files, and then importing the project instead of opening it, and have discovered that there is a problem with sync:
```
com.android.tools.idea.gradle.project.sync.ng.NewGradleSyncNotSupportedException: New Gradle Sync is not supported due to containing Kotlin modules
```

-------------

As for the rest of it, no changes for now.

-------------

> Do you have rust installed?

Yes, sure! I've done as instructed in the readme =D

> versions

rust: cargo 1.40.0 (bc8e4c8be 2019-11-22)
(I don't know how to check rust version, sorry)
android studio: 3.5.3
android sdk: 10.0, 6.0
ndk: 20.1.5948944
java: 8 Update 231
OS: Windows 10

**Comment by pietgeursen** [comment]
Oh man, I'm really sorry, I'm not sure how to debug this.

Have you tried just googling the error? I found this: https://stackoverflow.com/questions/56607089/new-gradle-sync-is-not-supported-due-to-containing-kotlin-modules-using-an-unsup
